bash sign_video_dev_coco_r50.sh
bash sign_video_dev_coco_swinl_5scale.sh
bash sign_video_dev_coco_swinl.sh
bash sign_video_dev_crowd_r50.sh
bash sign_video_dev_crowd_swinl_5scale.sh
bash sign_video_dev_crowd_swinl.sh
