bash sign_video_train_coco_r50.sh
bash sign_video_train_coco_swinl_5scale.sh
bash sign_video_train_coco_swinl.sh
bash sign_video_train_crowd_r50.sh
bash sign_video_train_crowd_swinl_5scale.sh
bash sign_video_train_crowd_swinl.sh
