bash sign_video_test_coco_r50.sh
bash sign_video_test_coco_swinl_5scale.sh
bash sign_video_test_coco_swinl.sh
bash sign_video_test_crowd_r50.sh
bash sign_video_test_crowd_swinl_5scale.sh
bash sign_video_test_crowd_swinl.sh
